#spring:
#  datasource:
#    username: root
#    password: root
#    url: jdbc:mysql://212.222.22.22:3306/user_db?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
#    driver-class-name: com.mysql.jdbc.Driver